pipeline {
  environment {
    // environment variables
    SOME_VAR = "SOME VALUE"
    // this assumes that "cred1" has been created on Jenkins Credentials
    CRED1 = credentials("RaviB")
    
    // this assumes that "cred2" has been created in Jenkins Credentials
    //CRED2 = credentials("RaviB")
    // Env variables can refer to other variables as well

	INBETWEEN = "Something in between"
    OTHER_VAR = "${SOME_VAR}"
  }

  agent any

  stages {
    stage("Credential Test") {
      steps {
	echo "hello world"
        // environment variables are not masked
        sh 'echo "SOME_VAR is $SOME_VAR"'
        sh 'echo "INBETWEEN is $INBETWEEN"'
        sh 'echo "OTHER_VAR is $OTHER_VAR"'

        // credential variables will be masked in console log but not in archived file
        sh 'echo $CRED1 > cred1.txt'
       // sh 'echo $CRED2 > cred2.txt'
        archive "**/*.txt"
      }
    }
  }
}
