pipeline {
  
agent any


environment {
    // environment variables
    SOME_VAR = "SOME VALUE"
	
//setting up cred1 env variable
cred1 = 'Credentials1'
    // this assumes that "cred1" has been created on Jenkins Credentials
//CRED1 = credentials('cred1')
    

//setting up cred2 env variable
cred2 = 'Credentials 2'    

// this assumes that "cred2" has been created in Jenkins Credentials
    //CRED2 = credentials('cred2')
    // Env variables can refer to other variables as well

	INBETWEEN = "Something in between"
    OTHER_VAR = "${SOME_VAR}"
  }

  
  stages {
    stage("Credential Test") {
      steps {
	echo "hello world"
        
    sh 'echo "cred1 is $cred1"'
	

// environment variables are not masked
        sh 'echo "SOME_VAR is $SOME_VAR"'
        sh 'echo "INBETWEEN is $INBETWEEN"'
        sh 'echo "OTHER_VAR is $OTHER_VAR"'

        // credential variables will be masked in console log but not in archived file
        sh 'echo $CRED1 > cred1.txt'
        sh 'echo $CRED2 > cred2.txt'
        archive "**/*.txt"
      }
    }
  }
}
