pipeline {
  agent { 
	docker{
		filename 'Dockerfile.alternate'
		dir 'docker'
		args "-v /tmp:/tmp -p 8000:8000"

		}
  	}
  stages {
    stage("Docker Test") {
      steps {
        sh 'cat /hi-there'
        sh 'echo "The answer is 42"'
      }
    }
  }
}
